const Highscore = ({ highscoreArray }) => {
  return (
    <>
      <tr>
        <td>1</td>
        <td>{highscoreArray[0][0]}</td>
        <td>{highscoreArray[0][1]}</td>
      </tr>
      <tr>
        <td>2</td>
        <td>{highscoreArray[1][0]}</td>
        <td>{highscoreArray[1][1]}</td>
      </tr>
      <tr>
        <td>3</td>
        <td>{highscoreArray[2][0]}</td>
        <td>{highscoreArray[2][1]}</td>
      </tr>
      <tr>
        <td>4</td>
        <td>{highscoreArray[3][0]}</td>
        <td>{highscoreArray[3][1]}</td>
      </tr>
      <tr>
        <td>5</td>
        <td>{highscoreArray[4][0]}</td>
        <td>{highscoreArray[4][1]}</td>
      </tr>
      <tr>
        <td>6</td>
        <td>{highscoreArray[5][0]}</td>
        <td>{highscoreArray[5][1]}</td>
      </tr>
      <tr>
        <td>7</td>
        <td>{highscoreArray[6][0]}</td>
        <td>{highscoreArray[6][1]}</td>
      </tr>
      <tr>
        <td>8</td>
        <td>{highscoreArray[7][0]}</td>
        <td>{highscoreArray[7][1]}</td>
      </tr>
      <tr>
        <td>9</td>
        <td>{highscoreArray[8][0]}</td>
        <td>{highscoreArray[8][1]}</td>
      </tr>
      <tr>
        <td>10</td>
        <td>{highscoreArray[9][0]}</td>
        <td>{highscoreArray[9][1]}</td>
      </tr>
    </>
  );
};

export default Highscore;
